name: Build with Gradle

on:
  pull_request:
    paths:
      - "back/**"
    branches: [main, develop, feature/backend-cicd-test]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Change directory
        run: cd ./back

      - name: Create application.properties
        run: |
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build without Test in Gradle
        run: ./gradlew build -x test
